### ISSUE TITLE
Feature request: Hide / unhide inherited members

### ISSUE THREAD

**Issue by andydandy74** [gtalarico/revitapidocs#122]
Hi Gui,
one thing I find myself wanting fairly often is the ability to hide all properties and methods that are not specific to the class I am currently looking at (i.e. everything inherited from any parent classes). It would be really cool to be able to have a toggle to hide/unhide those items...

**Example:**
Looking at ```SharedParameterElement``` this would isolate the ```GuidValue``` property since it is the only one not inherited from ```Element```.

**Comment by gtalarico** [comment]
Great suggestion. Should be fairly easy to implement.
I will take a look at this next time I get into the code.

**Comment by gtalarico** [comment]
Added to apidocs.co
