### ISSUE TITLE
Disqus comments not refreshed on node change

### ISSUE THREAD

**Issue by bimwood** [gtalarico/revitapidocs#131]
Hi Gui,
If I'm viewing a node with Disqus comments, when I change to a different node in the tree, the disqus comments stay the same (i.e. they aren't re-queried for the new node). So:
1. Open a node with Disqus comment like RevitLinkType.UnloadLocally: http://www.revitapidocs.com/2017/2b12bdb3-1505-960c-7cdb-e41a1295ff60.htm
2. Using the navigation tree, change to RevitLinkType.UpdateFromIFC.
3. You get the UpdateFromIFC content, but the UnloadLocally Disqus comments from Andrey and Luke.
 
![image](https://user-images.githubusercontent.com/5095961/42879505-d08001ba-8a88-11e8-94f7-0f4b6facb622.png)

Using Chrome Version 61.0.3163.100 (Official Build) (64-bit). Maybe fixed in later versions?

**Comment by gtalarico** [comment]
Hi David!
Thanks for reporting this. I am surprised no one has noticed this before. 
I know exactly issue is.

As a Workaround, refreshing the page should load the correct comment component.
Unfortunately, I can't say i plan on fixing this as I am working a completely new platform, so we will just have to accept this until the transition happens.
