### ISSUE TITLE
RotateElement Method: Angle value in degrees

### ISSUE THREAD

**Issue by AzubikeO** [gtalarico/revitapidocs#132]
Hey the angle parameter is shown to accept radians in the api docs but apparently its degrees. 

![image](https://user-images.githubusercontent.com/35468017/48099179-c34dfe00-e1ec-11e8-8ca2-6663054e02c0.png)

**Comment by gtalarico** [comment]
Thanks for the note @AzubikeO 

This repository however is to report bugs on the website site itself, not the content (search, navigation bugs, etc)
The content itself is authored by autodesk and published as is.
Unfortunately, at this point we do not support edits to the original content.

What we can do, however, is use the Comments section on that page to make this note to other users:
http://www.revitapidocs.com/2015/3968f4e8-759c-f975-6c1f-7de42be633ed.htm?section=seeAlsoToggle

## Example

![image](https://user-images.githubusercontent.com/9513968/48320166-5cfa1e80-e5e4-11e8-894a-d08d1a535e08.png)
