### ISSUE TITLE
RevitCommandId.LookupPostableCommandId documentation doesn't match type signature

### ISSUE THREAD

**Issue by tymokvo** [gtalarico/revitapidocs#133]
`RevitCommandId.LookupCommandId` takes a string as an argument
whereas
`RevitCommandId.LookupPostableCommandId` takes a member of the `PostableCommand` Enum
Its documentation reads:

"Looks up and retrieves the Revit command id with the given id string. "

Should be:

"Looks up and retrieves the Revit command id with the given `PostableCommand` member."

😸 Let me know if I can do anything else to help.

**Comment by gtalarico** [comment]
Hi @tymokvo - good eye! At least the syntax example shows the correct types.

Autodesk publishes these as immutable docs, so as I general rule, I don't make changes to published content as the change would be wiped if I need to regenerate the pages. 

The best we can do (for now, apidocs.co might fix this) is to add this a comment.
I have gone ahead and added it:
http://disq.us/p/209r30w

**Comment by tymokvo** [comment]
Ah got it! Thanks for the update.
