### ISSUE TITLE
Collapsible namespaces navigation collapses too fast

### ISSUE THREAD

**Issue by andydandy74** [gtalarico/revitapidocs#38]
First of all: Great stuff!
My issue is the following: When I click on one of the namespaces on the left hand side, it briefly expands to show all children but then collapses again after, say, two seconds. It's not a dealbreaker as the list of elements on the right hand side loads properly, but it's obviously not doing what it should.
Browser: Firefox 48.0.2 on Win 7
Also, I just checked this on another browser - In Internet Explorer 11 (Version 11.0.9600.18426) namespace items don't even expand at all.

**Comment by gtalarico** [comment]
Hi Andreas

Yeah it shouldn't collapse. I  haven't seen this behavior, but To be honest
I haven't done a lot of cross browser testing, only the latest chrome and
Firefox.

Are you clicking on the "text" , or on the background space around the
text?

**Comment by andydandy74** [comment]
Ah, interesting. I clicked on the text. When clicking on the background space it doesn't collapse (works in both browsers).

**Comment by gtalarico** [comment]
Yes, it's not very intuitive, but   I haven't been able to come up with a better solution for navigating tree Vs opening tree links

**Comment by gtalarico** [comment]
Some of the behaviors are built in to the js tree library I am using, but   feel free to suggest any ideas to improve it and I can try to l find a way around it

**Comment by gtalarico** [comment]
@andydandy74 
I have been thinking about this today, and I think a cursor change might be a nice/subtle visual cue to make the navigation slightly more intuitive:
http://beta.revitapidocs.com/2015/

**Comment by andydandy74** [comment]
Nice!
