### ISSUE TITLE
Some ideas for improving search

### ISSUE THREAD

**Issue by andydandy74** [gtalarico/revitapidocs#41]
Having worked with revitapidocs.com for a while now, here are some ideas of how the search UX could be improved: 
- Constrain search to certain categories (classes, methods, properties)
- Make search available on the landing page (perhaps move the search field into the page header?)
- Show search results as a new page (currently clicking on a search result will take me to that result but the browser's Back button will not let me return to the search results - which has led me to generally open search results in a new tab)
- Show more context in search results (e.g. if result is a property show the name of the class, too)

**Comment by gtalarico** [comment]
Thanks @andydandy74 great suggestions.

> Constrain search to certain categories (classes, methods, properties)

Will add to backlog

> 1. Make search available on the landing page (perhaps move the search field into the page header?)

Will add to backlog. I would think people usually target a specific API when they search. Maybe a text input with a filter dropdown filter for api year would work. See # 2

> 1. Show search results as a new page

New search features will trigger re-thinking the search backend and UI. I will keep this in mind. 

> 1. Show more context in search results (e.g. if result is a property show the name of the class, too)

Will add. Need to think about how to implement

Most of these improvments (except #2) require backend changes.
This was in my roadmap for 2.0: I need to create my own index of all pages in a DB (extract article type, namespace, etc) so I can query/filter/list by those parameters efficiently

Currently search only searches for article name from a json that stores the namespace tree,
which is fast but limited
https://raw.githubusercontent.com/gtalarico/revitapidocs/master/app/templates/json/ns_2015.json

In the meantime if you need better search, you can use the public Google Custom Search Engine:
https://cse.google.com/cse/publicurl?cx=014747897160299638528:fxtbgkrsxas

![image](https://cloud.githubusercontent.com/assets/9513968/18757195/d5622704-80c0-11e6-97d1-2d46f8387781.png)

**Comment by gtalarico** [comment]
Split into issues  #42 #43 #43 #44

**Comment by gtalarico** [comment]
Commit 378a17bf0b3f76584703777a7ebf937fa1635972
now saves scroll location and filter for search results
