### ISSUE TITLE
Better Results Interface

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/revitapidocs#45]
- Show Badge for type (method/property,etc)
- Include Link for related article, parent
- Consider Browser History so user can return to search results.

**Comment by gtalarico** [comment]
@andydandy I have put a new search prototype on the staging site if you want to take a peek, let me know if you have any thought. 
beta.revitapidocs.com

**Comment by gtalarico** [comment]
In progress :
- new indexed Db for better result Metadata 
- improved search algorithm now allows words out of order and separated by other characters
  +push history allows browser back to return to results

**Comment by andydandy74** [comment]
@gtalarico - This looks awesome! Browser history works and I love how the search results are noe presented. Also, it's great that class names are clickable as well!
Perhaps it would make sense to show all the relevant API version numbers of a particular item. Right now it seems that the search results always display 2015.

**Comment by andydandy74** [comment]
Also: I noticed a new behaviour on the beta site: If I search for a deprecated method it will show up in the search results, no matter which API version I chose as an entry point (nice!). However, when clicking on the result it may return a 404 depending on the entry point (API version) of my search (not so nice).
Steps to reproduce:
- Start search in Revit 2017 API context
- Search for "leaders"
- Click on any of the two Leaders properties in the search results: 404
- Do the same in Revit 2015/2016 API context and you'll get to the actual Leaders property page

**Comment by gtalarico** [comment]
Awesome. Thanks.
Yes, each entry will show the years it's available. 
Right now I'm just testing one year   as I am refining the parser that creates the index. It's a bit tricky because I have to manually extract the relationships (namespace, parent, parent link, etc) individually from each article page by page and try to handle all the different page types (namespace, class, enumeration, methods, etc) but it's getting there!

**Comment by gtalarico** [comment]
Yes, I have to figure out to handle the deprecated entries now that I have consolidated the entries in a single index. One options is to just show the entries for the year you are in. 
The other is to show all, but handle the 404 and show the years that page is available for (better)

**Comment by gtalarico** [comment]
@andydandy74 
All years added.
_when clicking on the result it may return a 404 depending on the entry point (API version)_ 
checkout out the update, let me know if works (clear cache or use incognito to be sure it's loading latest)

**Comment by andydandy74** [comment]
Yes, that looks great!

**Comment by gtalarico** [comment]
Stable RC on bc1cdfb63781e4c5da34f0c0ab4021c41c862cc1
