### ISSUE TITLE
Searching difficult in mobile version

### ISSUE THREAD

**Issue by andydandy74** [gtalarico/revitapidocs#71]
Hey @gtalarico - I wanted to look up something on revitapidocs.com on my phone today and had difficulties entering text into the search field as the animated example text in the serach field kept on going and going. Only after selecting a Revit version did it stop and I was able to enter text. How about disabling that text animation, at least for the mobile version?
iOS 10.0.2
BTW: Apart from that the mobile version works great!

**Comment by gtalarico** [comment]
I had that happen to me once, but wasn't able to reproduce, so I assumed it was ok,
Are you able to reproduce it consistently?
All animation should stop when you click select text box. 
Might be an ios browser compatibility issue.

I should probably turn off completely : P 
but I will turn off at least mobile when I get a chance.

**Comment by andydandy74** [comment]
Yes, I can definitely reproduce it consistently. Over and over again. ;-)

**Comment by gtalarico** [comment]
62d843f disables animation after user's first access.

**Comment by andydandy74** [comment]
Thanks!
