### ISSUE TITLE
Get Consent from Contributors 

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/revitapidocs#93]
@eirannejad and @andydandy74
I am testing a new concept on the latest version of the site (currently live at beta.reviapitocs.com), wanted to loop you in on this and get your consent.

I am calling it "Insights". The idea is to inject additional content into the pages to supplement official docs.
I wanted to start with Python.

The current test uses the following logic:
1. If a page has examples on it, search Github *public github api) for .py files that include the class/method being displayed.
2. If there are matches, inject links to those files into the examples section.

The reason I am including you here, is to make sure files are relevant, I decided to start by _limiting the search_ to a few authors that I know have quality RevitAPI/python content.
In the future, I am hoping to include forums, as well as a publicly maintained gist collections to make it easier for people to contribute to code samples and docs.

Would you both be ok with me including you in the list? Any other thoughts?

http://beta.revitapidocs.com/2017.1/b0a5f22c-6951-c3af-cd29-1f28f574035d.htm?section=exampleToggle
![image](https://cloud.githubusercontent.com/assets/9513968/23414109/cec5c12a-fda8-11e6-8de7-ef2ae9e3db8f.png)

**Comment by eirannejad** [comment]
I can't open the beta link. But feel free to link to pyRevit as you wish.
What happens if the scripts get changed and the reference is not there
anymore? Does it update regularly?

**Comment by andydandy74** [comment]
Can't open the link either, but I'd be honoured. Great idea.  Keep in mind though that the *.py files on my repo are all Dynamo-flavoured...

**Comment by eirannejad** [comment]
I forgot to say I'd be honoured :+1:

**Comment by gtalarico** [comment]
Sorry guys, try again later! 
AWS's server is ~experiencing issues~ completely down and it took away my S3 bucket :(

@eirannejad as for updates, content is pulled from Github search api live through an asynchronous call, and the only thing inserted is a link to the file, so it would always be updated. Perhaps in the future, I will do a little more "curating", ranking, and actually storing a copy, etc

@andydandy74 dynamo flavored should be fine, especially given that's were most novice users are first coming in contact with the API. 
That said, I will keep my eye it and will work on some ideas for selecting the most appropriate content
Cheers

**Comment by eirannejad** [comment]
Looks great!

**Comment by andydandy74** [comment]
Agreed. Out of curiosity - how will you handle code snippets for methods with multiple overloads?
Also, you might want to limit your search call on the Clockwork repo to this folder only since that is the only one that is actually being actively maintained: https://github.com/andydandy74/ClockworkForDynamo/tree/master/nodes/1.x/python

**Comment by gtalarico** [comment]
_how will you handle code snippets for methods with multiple overloads?_
Good question, not sure yet . Github api for code search is limited, and I don't think I can use regexs.
I will see if I can add a filter to that location
